

services:
  # PostgreSQL service
  postgres:
    image: postgres:16.4  # You can specify any version of PostgreSQL
    container_name: postgres-container
    environment:
      POSTGRES_USER: user  # Default user for PostgreSQL
      POSTGRES_PASSWORD: password  # Password for the default user
      POSTGRES_DB: worker-app  # Name of the database
    ports:
      - "5431:5431"  # Expose PostgreSQL on port 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist data

  # Spring Boot Application
  springboot:
    build: /home/scvitan/Desktop/worker-app-docker/work-app  # Path to your Spring Boot Dockerfile
    container_name: springboot-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/worker-app  # Connect to PostgreSQL service
      SPRING_DATASOURCE_USERNAME: user  # Database user
      SPRING_DATASOURCE_PASSWORD: mypassword  # Database password
    ports:
      - "8080:8080"  # Expose Spring Boot app on port 8080
    depends_on:
      - postgres  # Ensure PostgreSQL is up before starting Spring Boot

volumes:
  postgres-data:  # Named volume for PostgreSQL data persistence
