package com.example.workapp.enums;

public enum StateOfEmploymentOfInterest {
    BOSNIA_AND_HERZEGOVINA, SERBIA, KOSOVO, ALBANIA, MACEDONIA, CROATIA, SLOVENIA, AUSTRIA, ITALY, GERMANY, BELGIUM, NETHERLANDS, FRANCE, USA
}
